### ISSUE TITLE
Issue found in your code

### ISSUE THREAD

**Issue by sarathjnair** [HarishRaja0211/Demo_Practice#2]
Hi Harish,
I've found an issue in your code. The program asks for number input when executing, but if I give any strings as input the program crashes with ValueError. It would be good if there is a fail-safe mechanism while accepting user input.

![Screenshot from 2023-01-09 14-55-55](https://user-images.githubusercontent.com/115861318/211276573-6d516a51-0992-4953-adfc-bf8955ae664c.png)

**Comment by HarishRaja0211** [comment]
i have solved issue
